let a = 6;
let b = 9;
a++;
console.log(a + b);
console.log(a - b);
console.log(b / a);
console.log(a ** 2 * b);
console.log(b % a);
console.log(`${a} + ${b}`);
console.log('a' + b);
console.log(b + false);
console.log(null + a);
console.log(a + true + ' b');
console.log(a + undefined);
console.log(a - a);
console.log(2 > 1);
console.log(7 <= 9);
console.log(5 == 1);
console.log(15 != 7);
console.log(7 > 7);
console.log('я' < 'Я');
console.log('торт' >= 'тон');
console.log('075' == 12);
console.log('075' == 75);
console.log('05' === 5);
console.log('тара' === 'тара');
console.log(null == undefined);
console.log(null == 0);
console.log(null == false);
console.log(1 === true);
console.log(true == 1);
console.log('Лавка' === undefined);
